### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by ways** [entur/api-examples#1]
Hi

Would be nice if you could post more examples. Like just a basic curl to fetch departures for a stop.

**Comment by draperunner** [comment]
Hi! I am not sure if this repo is still going to be maintained. Please refer to https://developer.entur.org for documentation and examples.

To get departures for a stop, JourneyPlanner is the API you are looking for: https://developer.entur.org/pages-journeyplanner-journeyplanner That page has some examples. 

You can play around with the GraphQL API here: https://api.entur.io/journey-planner/v2/ide/. To get a cURL call, you can do the call you want in the GraphQL editor with the network console open, and then (at least in Chrome) you can right-click the call and select Copy -> Copy as cURL.

**Comment by ways** [comment]
Ah, thanks. ( Copy -> Copy as cURL is in firefox too. Nice trick! )
