### ISSUE TITLE
Hente ut avvik og problemer

### ISSUE THREAD

**Issue by ways** [entur/api-examples#3]
Hi

I've still got some way to go. =)

Where do I find extra info like one can see here:

Example: https://en-tur.no/stops-on-line?id=NSR%3AStopPlace%3A60034
"19 Majorstuen
Trikken har høyt gulv og trappetrinn, og det er dessverre ikke mulig å komme seg om bord med rullestol."

And problems like when trips are cancelled.

**Comment by draperunner** [comment]
Notices and situations. 

Notices are information messages like your example above. Situations are more like warnings like "The stop place has temporarily been moved" and cancellations.

https://api.entur.io/journey-planner/v2/ide/?query={%20%20stopPlace(%20%20%20%20id%3A"NSR%3AStopPlace%3A60034"%20%20)%20%20{%20%20%20%20name%20%20%20%20id%20%20%20%20estimatedCalls%20{%20%20%20%20%20%20expectedDepartureTime%20%20%20%20%20%20destinationDisplay%20{%20%20%20%20%20%20%20%20frontText%20%20%20%20%20%20}%20%20%20%20%20%20serviceJourney%20{%20%20%20%20%20%20%20%20line%20{%20%20%20%20%20%20%20%20%20%20publicCode%20%20%20%20%20%20%20%20%20%20transportMode%20%20%20%20%20%20%20%20%20%20situations%20{%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20situations%20{%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20summary%20{%20%20%20%20%20%20%20%20%20%20%20%20value%20%20%20%20%20%20%20%20%20%20%20%20language%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20notices%20{%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20text%20%20%20%20%20%20%20%20}%20%20%20%20%20%20}%20%20%20%20}%20%20}}

**Comment by ways** [comment]
Thank you for explaining.
